
# Get all professors.

GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/professors


###
# Get single professor.

GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/professors/c78d464e-9df9-4b63-9268-60426b6fdcfa


###
# GET NON EXISTENT

GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/professors/gh8d464e-9df9-4b63-9268-60426b6fdcgb

###

# Create character portrait.

PUT http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/professors/c78d464e-9df9-4b63-9268-60426b6fdcfa/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="professor.png'

< src/main/resources/prof.jpg
--boundary--

###

GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/professors/c78d464e-9df9-4b63-9268-60426b6fdcfa/image

###

DELETE http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/professors/c78d464e-9df9-4b63-9268-60426b6fdcfa/image


################################################################################################


GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses

###
GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/3ce1d5ba-8105-4eb0-b7af-d1f87bc92c98


###
PUT http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/
Content-Type: application/json

{
  "name": "NewCreated",
  "startDate": "2023-11-05T00:00:00Z"
}

###

DELETE http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/

###

PATCH http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/
Content-Type: application/json

{
  "name": "anotherName",
  "startDate": "2026-12-25T00:00:00Z"
}


###

GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/lectures/

###

PUT http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/lectures/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
Content-Type: application/json

{
  "name": "Lecture 1"
}

###

GET http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/lectures/ff327e8a-77c0-4f9b-90a2-89e16895d1e1


###

PATCH http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/lectures/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
Content-Type: application/json

{
  "date": "Lecture 2"
}

###

DELETE http://localhost:9080/prof-hub-1.0-SNAPSHOT/api/courses/f4b2be36-2512-44ea-8cc7-9d9c2fc86baf/lectures/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
